apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      containers:
        - name: node-monitor-app
          image: node-monitor-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
